/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iac.app;

//import static iac.app.Profilepage.;
import static iac.app.MyPetpage.MP;
import static iac.app.AddPet.*;
import static iac.app.MyPetpage.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nooralsharif
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public static AddPet AP = new AddPet();
    public File database = new File("Database.txt");
    

    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        AppLogoWIGHTbackground4 = new javax.swing.JPanel();
        AppLogo5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        mypetsbutton = new javax.swing.JButton();
        appbutton = new javax.swing.JButton();
        storebutton = new javax.swing.JButton();
        profilebutton = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        backgroundpic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 715));

        jPanel3.setMaximumSize(new java.awt.Dimension(500, 715));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 715));
        jPanel3.setLayout(null);

        AppLogoWIGHTbackground4.setBackground(new java.awt.Color(255, 255, 255));

        AppLogo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppLogo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/logo2.png"))); // NOI18N

        javax.swing.GroupLayout AppLogoWIGHTbackground4Layout = new javax.swing.GroupLayout(AppLogoWIGHTbackground4);
        AppLogoWIGHTbackground4.setLayout(AppLogoWIGHTbackground4Layout);
        AppLogoWIGHTbackground4Layout.setHorizontalGroup(
            AppLogoWIGHTbackground4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppLogoWIGHTbackground4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(AppLogo5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        AppLogoWIGHTbackground4Layout.setVerticalGroup(
            AppLogoWIGHTbackground4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppLogoWIGHTbackground4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AppLogo5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(AppLogoWIGHTbackground4);
        AppLogoWIGHTbackground4.setBounds(90, 30, 300, 130);

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mypetsbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mypetsbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/petpaw.png"))); // NOI18N
        mypetsbutton.setText("My Pets");
        mypetsbutton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mypetsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mypetsbuttonActionPerformed(evt);
            }
        });

        appbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        appbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/calendar.png"))); // NOI18N
        appbutton.setText("Appointment");
        appbutton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        appbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appbuttonActionPerformed(evt);
            }
        });

        storebutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        storebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/cart.png"))); // NOI18N
        storebutton.setText("Pet Store");
        storebutton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        profilebutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        profilebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/username copy.png"))); // NOI18N
        profilebutton.setText("Profile");
        profilebutton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profilebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mypetsbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(storebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(mypetsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(appbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(storebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(40, 180, 420, 430);

        logout.setBackground(new java.awt.Color(255, 153, 0));
        logout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel3.add(logout);
        logout.setBounds(170, 630, 130, 60);

        backgroundpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/background photo.jpg"))); // NOI18N
        jPanel3.add(backgroundpic);
        backgroundpic.setBounds(0, 0, 500, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void mypetsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mypetsbuttonActionPerformed
        // TODO add your handling code here:
        
        new MyPetpage().setVisible(true);
        
        try {

            File petnames = new File("pets names.txt");
            
            BufferedReader br = new BufferedReader(new FileReader(petnames));

            Scanner sc2 = new Scanner(petnames);

            String petname = "pet name:";

            boolean found = false; // added this variable

            while (sc2.hasNextLine()) {

                String input = sc2.nextLine();

                if (input.equals(petname)) {
                    found = true;
                    MyPetpage.pet1.setText(sc2.nextLine());
                    
                }
            }

            if (!found) { // added the contents of the previously existing else statement here, outside the while
                JOptionPane.showMessageDialog(null,
                        "Database is empty.",
                        "Error Message",
                        JOptionPane.ERROR_MESSAGE);

                //new SignupPT1().setVisible(true);
            }

            br.close();

        } catch (IOException ex) {
            Logger.getLogger(LogInpage.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.dispose();

        
        new MyPetpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mypetsbuttonActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:

        new Startpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void profilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebuttonActionPerformed
        // TODO add your handling code here:

        new Profilepage().setVisible(true);
        
        try {

            PrintWriter fileWriter = new PrintWriter(new FileWriter(database, true));

            BufferedWriter bw = new BufferedWriter(fileWriter);
            BufferedReader br = new BufferedReader(new FileReader(database));

            Scanner sc2 = new Scanner(database);

            //String enterusername = usernamebox.getText();
            //char[] enterpassword = passwordbox.getPassword();
            String name = "First Name:";
            String last = "Last Name:";
            String id = "ID:";
            String bd = "Birth Date:";
            String pn = "Phone Number:";
            String email = "Email:";

            String cn = "Card Number:";
            String cvv = "cvv:";
            String exp = "Exp. Date:";
            String zip = "Zip Code:";
            String ba = "Billing Address:";

            boolean found = false; // added this variable

            while (sc2.hasNextLine()) {

                String input = sc2.nextLine();

                if (input.equals(name)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    Profilepage.Fnamebox2.setText(sc2.nextLine());
                }

                if (input.equals(last)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    Profilepage.Lnamebox.setText(sc2.nextLine());
                }

                if (input.equals(id)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    Profilepage.IDbox.setText(sc2.nextLine());
                }

                if (input.equals(bd)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    Profilepage.birthdatebox.setText(sc2.nextLine());
                }

                if (input.equals(pn)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    Profilepage.phonenumbox.setText(sc2.nextLine());
                }

                if (input.equals(email)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    Profilepage.emailbox.setText(sc2.nextLine());
                }

                if (input.equals(cn)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    Profilepage.cardnumbox.setText(sc2.nextLine());
                }

                if (input.equals(cvv)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    Profilepage.cvvbox.setText(sc2.nextLine());

                }

                if (input.equals(exp)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    Profilepage.expdatebox.setText(sc2.nextLine());
                }

                if (input.equals(zip)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    Profilepage.zipcodebox.setText(sc2.nextLine());
                }

                if (input.equals(ba)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    Profilepage.billingaddbox.setText(sc2.nextLine());
                }

            }

            if (!found) { // added the contents of the previously existing else statement here, outside the while
                JOptionPane.showMessageDialog(null,
                        "Database is empty.",
                        "Error Message",
                        JOptionPane.ERROR_MESSAGE);

                //new SignupPT1().setVisible(true);
            }

            bw.close();

        } catch (IOException ex) {
            Logger.getLogger(LogInpage.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.dispose();

    }//GEN-LAST:event_profilebuttonActionPerformed

    private void appbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appbuttonActionPerformed
        new make_an_appointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                //javax.swing.UIManager.setLookAndFeebackgroundpicgetClassName());
                break;
            }
        } //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppLogo5;
    private javax.swing.JPanel AppLogoWIGHTbackground4;
    private javax.swing.JButton appbutton;
    private javax.swing.JLabel backgroundpic;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logout;
    private javax.swing.JButton mypetsbutton;
    private javax.swing.JButton profilebutton;
    private javax.swing.JButton storebutton;
    // End of variables declaration//GEN-END:variables
}
