/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iac.app;

import java.io.*;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nooralsharif
 */
public class LogInpage extends javax.swing.JFrame {

    public static String enterusername;
    /**
     * Creates new form LogInpage
     */
    
    
    public File database = new File("Database.txt");
    
    
    public LogInpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TEALBox = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bluebox1 = new javax.swing.JPanel();
        usernamebox = new javax.swing.JTextField();
        passwordlogo = new javax.swing.JLabel();
        usernamelogo = new javax.swing.JLabel();
        passwordbox = new javax.swing.JPasswordField();
        remmemberme = new javax.swing.JCheckBox();
        cancel = new javax.swing.JButton();
        nextlogin = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 715));
        jPanel2.setLayout(null);

        TEALBox.setBackground(new java.awt.Color(0, 153, 153));
        TEALBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/square logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Member");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("Login");

        javax.swing.GroupLayout TEALBoxLayout = new javax.swing.GroupLayout(TEALBox);
        TEALBox.setLayout(TEALBoxLayout);
        TEALBoxLayout.setHorizontalGroup(
            TEALBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TEALBoxLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(TEALBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        TEALBoxLayout.setVerticalGroup(
            TEALBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TEALBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TEALBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TEALBoxLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(TEALBox);
        TEALBox.setBounds(70, 70, 370, 120);

        bluebox1.setBackground(new java.awt.Color(0, 204, 204));
        bluebox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        usernamebox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernamebox.setForeground(new java.awt.Color(204, 204, 204));
        usernamebox.setText("USERNAME");
        usernamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameboxActionPerformed(evt);
            }
        });

        passwordlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/password.png"))); // NOI18N

        usernamelogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/username.png"))); // NOI18N

        passwordbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordbox.setForeground(new java.awt.Color(204, 204, 204));
        passwordbox.setText("PASSWORD");
        passwordbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordboxActionPerformed(evt);
            }
        });

        remmemberme.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        remmemberme.setText("Remmember me");
        remmemberme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remmembermeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bluebox1Layout = new javax.swing.GroupLayout(bluebox1);
        bluebox1.setLayout(bluebox1Layout);
        bluebox1Layout.setHorizontalGroup(
            bluebox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bluebox1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(bluebox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(bluebox1Layout.createSequentialGroup()
                        .addComponent(usernamelogo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bluebox1Layout.createSequentialGroup()
                        .addComponent(passwordlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bluebox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordbox)
                            .addGroup(bluebox1Layout.createSequentialGroup()
                                .addComponent(remmemberme, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(23, 23, 23))
        );
        bluebox1Layout.setVerticalGroup(
            bluebox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluebox1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(bluebox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamelogo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(bluebox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordbox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(remmemberme)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.add(bluebox1);
        bluebox1.setBounds(70, 260, 370, 240);

        cancel.setBackground(new java.awt.Color(255, 153, 0));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel);
        cancel.setBounds(70, 560, 160, 60);

        nextlogin.setBackground(new java.awt.Color(255, 153, 0));
        nextlogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nextlogin.setForeground(new java.awt.Color(255, 255, 255));
        nextlogin.setText("Login");
        nextlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextloginActionPerformed(evt);
            }
        });
        jPanel2.add(nextlogin);
        nextlogin.setBounds(290, 560, 160, 60);

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/background photo.jpg"))); // NOI18N
        jPanel2.add(BackgroundImage);
        BackgroundImage.setBounds(0, 0, 500, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameboxActionPerformed

    private void passwordboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordboxActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        new Startpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void nextloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextloginActionPerformed
        // TODO add your handling code here:

        try {

            PrintWriter fileWriter = new PrintWriter(new FileWriter(database, true));
            
            BufferedWriter bw = new BufferedWriter(fileWriter);
            BufferedReader br = new BufferedReader(new FileReader(database));

            
            Scanner sc2 = new Scanner(database);

            enterusername = usernamebox.getText();
            char[] enterpassword = passwordbox.getPassword();

            String username = "Username";
            String password = "Password";

            String check_username;
            String check_password;
            String check_password1;
            
            boolean found = false; // added this variable
            
            while (sc2.hasNextLine()) {

                String input = sc2.nextLine();

                
                if (input.equals(username)) {

                    found = true;
                    
                    check_username = sc2.nextLine();
                    check_password1 = sc2.nextLine();
                    check_password = sc2.nextLine();
                    
                    if(check_username.equals(enterusername) && check_password.equals(Arrays.toString(enterpassword).replace("[", "").replace("]", "").replace(", ", ""))){
                        
                        System.out.println("succeed!");

                        System.out.println(username);
                        System.out.println("\tusename in file is: " + check_username);
                        System.out.println("\tusername written is: " + enterusername);
                        
                        System.out.println("\nsucceed!");

                        System.out.println(password);
                        System.out.println("\tpassword in file is: " + check_password);
                        System.out.println("\tpassword written is: " + Arrays.toString(enterpassword).replace("[", "").replace("]", "").replace(", ", ""));

                        new Homepage().setVisible(true);
                        this.dispose();
                    }
                    
                    else if(!check_username.equals(enterusername)){
                        
                        new Homepage().dispose();
                        
                        JOptionPane.showMessageDialog(null,
                        "Invalid username. Try again.",
                        "Error Message",
                        JOptionPane.ERROR_MESSAGE);
                        
                        
                    }else if(!check_password.equals(Arrays.toString(enterpassword).replace("[", "").replace("]", "").replace(", ", ""))){
                        JOptionPane.showMessageDialog(null,
                        "Invalid password. Try again.",
                        "Error Message",
                        JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            
            if (!found) { // added the contents of the previously existing else statement here, outside the while
                JOptionPane.showMessageDialog(null,
                        "User not found. please Signup.",
                        "Error Message",
                        JOptionPane.ERROR_MESSAGE);

                new SignupPT1().setVisible(true);
            }
            
            bw.close();

        } catch (IOException ex) {
            Logger.getLogger(LogInpage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_nextloginActionPerformed

    private void remmembermeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remmembermeActionPerformed
        // TODO add your handling code here:
        
        try {
            
            PrintWriter fileWriter = new PrintWriter(new FileWriter(database, true));
            
            BufferedWriter bw = new BufferedWriter(fileWriter);
            BufferedReader br = new BufferedReader(new FileReader(database));
            
            Scanner sc2 = new Scanner(database);

            String password = "Password";
            
            while (sc2.hasNextLine()) {

                Scanner s2 = new Scanner(sc2.nextLine());

                while (s2.hasNext()) {

                    String line = s2.next();
                    //System.out.println(line);
                    if(line.equals(password)){
                        
                        passwordbox.setText(sc2.nextLine());
                        //sc2.nextLine();
                    }
                    
                }
            }

        } catch (IOException ex) {
                Logger.getLogger(LogInpage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_remmembermeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel TEALBox;
    private javax.swing.JPanel bluebox1;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nextlogin;
    private javax.swing.JPasswordField passwordbox;
    private javax.swing.JLabel passwordlogo;
    private javax.swing.JCheckBox remmemberme;
    private javax.swing.JTextField usernamebox;
    private javax.swing.JLabel usernamelogo;
    // End of variables declaration//GEN-END:variables
}
