package iac.app;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static iac.app.ReserveDoctor_BOOKING.RB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jana Omar Baqays 1805288.
 */
public class make_an_appointment extends javax.swing.JFrame {

    /**
     * created a new form make_an_appointment.
     */
    public static make_an_appointment MA = new make_an_appointment();

    /**
     * Creates new form make_an_appointment.
     */
    public make_an_appointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        Back_Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        groomingSevices_Button = new javax.swing.JButton();
        Doctor_Button = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/animal.png"))); // NOI18N
        LOGO.setText("Make An Appointments");
        getContentPane().add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 360, 100));

        Back_Button.setBackground(new java.awt.Color(255, 153, 0));
        Back_Button.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Back_Button.setForeground(new java.awt.Color(255, 255, 255));
        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        groomingSevices_Button.setBackground(new java.awt.Color(153, 204, 0));
        groomingSevices_Button.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        groomingSevices_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/pet-shampoo.png"))); // NOI18N
        groomingSevices_Button.setText("Grooming Services");
        groomingSevices_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groomingSevices_ButtonActionPerformed(evt);
            }
        });

        Doctor_Button.setBackground(new java.awt.Color(153, 204, 0));
        Doctor_Button.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Doctor_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/vaccine.png"))); // NOI18N
        Doctor_Button.setText("Doctor");
        Doctor_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doctor_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(groomingSevices_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Doctor_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(groomingSevices_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Doctor_Button)
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 290, 230));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/background photo.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 715));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * This method is called Back_ButtonActionPerformed go to the Previous form.
     *
     * @param ActionEvent the action of button will run the code inside the
     * method and display the form we want it.
     */
    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        new Homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_ButtonActionPerformed
    /**
     * This method is called groomingSevices_ButtonActionPerformed go to the
     * grooming Sevices form.
     *
     * @param ActionEvent the action of button will run the code inside the
     * method and display the form we want it.
     */
    private void groomingSevices_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groomingSevices_ButtonActionPerformed
        //new Reserve_Grooming_Services_And_Pet().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_groomingSevices_ButtonActionPerformed
    /**
     * This method is called Doctor_ButtonActionPerformed go to the doctor form.
     *
     * @param ActionEvent the action of button will run the code inside the
     * method and display the form we want it and print in JComboBox the
     * appointments.
     */
    private void Doctor_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doctor_ButtonActionPerformed
        MA.setVisible(false);
        try {
            RB.ListOfAppointments();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ReserveDoctor_BOOKING.class.getName()).log(Level.SEVERE, null, ex);
        }
        RB.setVisible(true);
    }//GEN-LAST:event_Doctor_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(make_an_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(make_an_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(make_an_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(make_an_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MA.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Doctor_Button;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton groomingSevices_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
