package iac.app;

import java.awt.List;
import java.io.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author noor alsharif and jana baqays
 */
public class MyPetpage extends javax.swing.JFrame {

    /**
     * Is a public list value that save in it the all pets of user
     * that readed from the File pet names.
     */
    public static List MyPets = new List();

    /**
     * created a new form MyPetpage.
     */
    public static MyPetpage MP = new MyPetpage();

    /**
     * Creates new form MyPetpage.
     */
    public MyPetpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pet1 = new javax.swing.JButton();
        pet2 = new javax.swing.JButton();
        pet3 = new javax.swing.JButton();
        pet4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 715));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("My Pets");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/petpaw.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 30, 370, 110);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 600, 120, 60);

        Add.setBackground(new java.awt.Color(255, 153, 0));
        Add.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add);
        Add.setBounds(290, 600, 120, 60);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        pet1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/petpaw.png"))); // NOI18N
        pet1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet1ActionPerformed(evt);
            }
        });

        pet2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pet2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/petpaw.png"))); // NOI18N
        pet2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet2ActionPerformed(evt);
            }
        });

        pet3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pet3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/petpaw.png"))); // NOI18N
        pet3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pet3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet3ActionPerformed(evt);
            }
        });

        pet4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pet4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/petpaw.png"))); // NOI18N
        pet4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pet4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pet1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(pet2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pet3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pet4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pet1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pet2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pet3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pet4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(60, 170, 370, 400);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/background photo.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 720);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(60, 310, 370, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * This method is called jButton1ActionPerformed go to the Homepage form.
     *
     * @param ActionEvent the action of button will run the code inside the
     * method and display the form we want it.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        new Homepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * This method is called pet1ActionPerformed go to the pet1 information form.
     *
     * @param ActionEvent the action of button will run the code inside the
     * method and display the form we want it.
     */
    private void pet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet1ActionPerformed
        // TODO add your handling code here:

        String petname = pet1.getText();
        String petInfo = "";
        
        for (int i = 0; i < MyPets.getItemCount(); i++) {
            
            String[] pet = MyPets.getItem(i).split(",");
            
            if (petname.equals(pet[1])) {
                
                petInfo = MyPets.getItem(i);
                
            }
            
        }
        
        PetInfo pi = new PetInfo();
        
        pi.setVisible(true);
        
        pi.setPetInfo(petInfo);
        
        this.dispose();

    }//GEN-LAST:event_pet1ActionPerformed
    /**
     * This method is called AddActionPerformed go to the add a new pet form.
     *
     * @param ActionEvent the action of button will run the code inside the
     * method and display the form we want it.
     */
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        new AddPet().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddActionPerformed
    /**
     * This method is called pet2ActionPerformed go to the pet2 information form.
     *
     * @param ActionEvent the action of button will run the code inside the
     * method and display the form we want it.
     */
    private void pet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet2ActionPerformed
        // TODO add your handling code here:
        
        String petname = pet2.getText();
        String petInfo = "";
        
        for (int i = 0; i < MyPets.getItemCount(); i++) {
            
            String[] pet = MyPets.getItem(i).split(",");
            
            if (petname.equals(pet[1])) {
                
                petInfo = MyPets.getItem(i);
                
            }
            
        }
        
        PetInfo pi = new PetInfo();
        
        pi.setVisible(true);
        
        pi.setPetInfo(petInfo);
        
        this.dispose();
    }//GEN-LAST:event_pet2ActionPerformed
    /**
     * This method is called pet3ActionPerformed go to the pet3 information form.
     *
     * @param ActionEvent the action of button will run the code inside the
     * method and display the form we want it.
     */
    private void pet3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet3ActionPerformed
        // TODO add your handling code here:
        
        String petname = pet3.getText();
        String petInfo = "";
        
        for (int i = 0; i < MyPets.getItemCount(); i++) {
            
            String[] pet = MyPets.getItem(i).split(",");
            
            if (petname.equals(pet[1])) {
                
                petInfo = MyPets.getItem(i);
                
            }
            
        }
        
        PetInfo pi = new PetInfo();
        
        pi.setVisible(true);
        
        pi.setPetInfo(petInfo);
        
        this.dispose();
    }//GEN-LAST:event_pet3ActionPerformed
    /**
     * This method is called pet4ActionPerformed go to the pet4 information form.
     *
     * @param ActionEvent the action of button will run the code inside the
     * method and display the form we want it.
     */
    private void pet4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet4ActionPerformed
        // TODO add your handling code here:
        
        String petname = pet4.getText();
        String petInfo = "";
        
        for (int i = 0; i < MyPets.getItemCount(); i++) {
            
            String[] pet = MyPets.getItem(i).split(",");
            
            if (petname.equals(pet[1])) {
                
                petInfo = MyPets.getItem(i);
                
            }
            
        }
        
        PetInfo pi = new PetInfo();
        
        pi.setVisible(true);
        
        pi.setPetInfo(petInfo);
        
        this.dispose();
    }//GEN-LAST:event_pet4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyPetpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyPetpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyPetpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyPetpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form and read pets' names and print it in buttons*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MP.readPets();
                MP.setVisible(true);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JButton pet1;
    public static javax.swing.JButton pet2;
    public static javax.swing.JButton pet3;
    public static javax.swing.JButton pet4;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void readPets() {
        try {

            Scanner sc = new Scanner(new File("pets names.txt"));
            int petnum = 0;
            while (sc.hasNextLine()) {
                String[] p = sc.nextLine().split(",");
                switch (petnum){
                    case 0: pet1.setText(p[1]);
                    break;
                    case 1: pet2.setText(p[1]);
                    break;
                    case 2: pet3.setText(p[1]);
                    break;
                    case 3: pet4.setText(p[1]);
                    break;
                    default : petnum = 0;
                }
                petnum++;
            }

            sc.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MyPetpage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
