/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iac.app;
import static iac.app.MyPetpage.MP;
import java.awt.List;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;

/**
 *
 * @author Jana Omar Baqays 1805288
 */
public class PetInfo extends javax.swing.JFrame {
    
    /**
     *
     */
    public static PetInfo PI = new PetInfo();

    /**
     * Creates new form PetInfo
     */
    public PetInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOGO = new javax.swing.JLabel();
        Animal_photo = new javax.swing.JLabel();
        name_lable = new javax.swing.JLabel();
        Animal_Name = new javax.swing.JTextField();
        age_lable = new javax.swing.JLabel();
        Animal_Age = new javax.swing.JTextField();
        kind_lable = new javax.swing.JLabel();
        Animal_Kind = new javax.swing.JTextField();
        VaccinationSchedule_lable = new javax.swing.JLabel();
        VaccinationSchedule = new javax.swing.JScrollPane();
        Vaccination_Schedule = new javax.swing.JTextArea();
        Back_Button = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/pet info.png"))); // NOI18N
        LOGO.setText("Pet information");
        getContentPane().add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        Animal_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/pet2.png"))); // NOI18N
        getContentPane().add(Animal_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 60, 60));

        name_lable.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        name_lable.setText("Animal's Name :");
        getContentPane().add(name_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        Animal_Name.setEnabled(false);
        getContentPane().add(Animal_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 110, 30));

        age_lable.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        age_lable.setText("Animal's Age :");
        getContentPane().add(age_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        Animal_Age.setEnabled(false);
        getContentPane().add(Animal_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 110, 30));

        kind_lable.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        kind_lable.setText("Animal's Kind :");
        getContentPane().add(kind_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        Animal_Kind.setEnabled(false);
        getContentPane().add(Animal_Kind, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 110, 30));

        VaccinationSchedule_lable.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        VaccinationSchedule_lable.setText("Animal's Vaccination Schedule :");
        getContentPane().add(VaccinationSchedule_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        Vaccination_Schedule.setColumns(20);
        Vaccination_Schedule.setRows(5);
        Vaccination_Schedule.setEnabled(false);
        VaccinationSchedule.setViewportView(Vaccination_Schedule);

        getContentPane().add(VaccinationSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 130, -1));

        Back_Button.setBackground(new java.awt.Color(255, 153, 0));
        Back_Button.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Back_Button.setForeground(new java.awt.Color(255, 255, 255));
        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/background photo.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        PI.setVisible(false);
        MyPetpage PP = new MyPetpage();
        PP.readPets();
        PP.setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PI.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Animal_Age;
    public static javax.swing.JTextField Animal_Kind;
    public static javax.swing.JTextField Animal_Name;
    private javax.swing.JLabel Animal_photo;
    private javax.swing.JButton Back_Button;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel LOGO;
    private javax.swing.JScrollPane VaccinationSchedule;
    private javax.swing.JLabel VaccinationSchedule_lable;
    public static javax.swing.JTextArea Vaccination_Schedule;
    private javax.swing.JLabel age_lable;
    private javax.swing.JLabel kind_lable;
    private javax.swing.JLabel name_lable;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param pet
     */
    public void setPetInfo(String pet) {
        String [] petInfo = pet.split(",");
        Animal_Name.setText(petInfo[1]);
        Animal_Age.setText(petInfo[2]);
        Animal_Kind.setText(petInfo[3]);
        Vaccination_Schedule.setText(petInfo[4]);
    }
}
