/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iac.app;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nooralsharif
 */
public class profileedit extends javax.swing.JFrame {

    /**
     * Creates new form profileedit
     */
    public static File database = new File("Database.txt");

    public profileedit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bluebox4 = new javax.swing.JPanel();
        personalinfo2 = new javax.swing.JLabel();
        Fnamebox2 = new javax.swing.JTextField();
        Lnamebox = new javax.swing.JTextField();
        IDbox = new javax.swing.JTextField();
        birthdatebox = new javax.swing.JTextField();
        phonenumbox = new javax.swing.JTextField();
        emailbox = new javax.swing.JTextField();
        Fname = new javax.swing.JLabel();
        Lname = new javax.swing.JLabel();
        IDnum = new javax.swing.JLabel();
        Birthdate = new javax.swing.JLabel();
        Phonenum = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        bluebox5 = new javax.swing.JPanel();
        Cardinfo = new javax.swing.JLabel();
        cardnumbox = new javax.swing.JTextField();
        expdatebox = new javax.swing.JTextField();
        cvvbox = new javax.swing.JTextField();
        zipcodebox = new javax.swing.JTextField();
        billingaddbox = new javax.swing.JTextField();
        cardnum = new javax.swing.JLabel();
        expdate = new javax.swing.JLabel();
        cvv = new javax.swing.JLabel();
        zipcode = new javax.swing.JLabel();
        billingadd = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 715));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 715));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 715));
        jPanel1.setSize(new java.awt.Dimension(500, 715));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Profile");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/username copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 40, 370, 80);

        bluebox4.setBackground(new java.awt.Color(0, 204, 204));
        bluebox4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        personalinfo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        personalinfo2.setText("Personal Information");

        Fnamebox2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Fnamebox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fnamebox2ActionPerformed(evt);
            }
        });

        Lnamebox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Lnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameboxActionPerformed(evt);
            }
        });

        IDbox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        IDbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDboxActionPerformed(evt);
            }
        });

        birthdatebox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        birthdatebox.setText(" XX / XX / XXXX");
        birthdatebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateboxActionPerformed(evt);
            }
        });

        phonenumbox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        phonenumbox.setText("5XXXXXXXX");
        phonenumbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumboxActionPerformed(evt);
            }
        });

        emailbox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        emailbox.setText("EXAMPLE @ EXAMPLE.COM");
        emailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailboxActionPerformed(evt);
            }
        });

        Fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fname.setText("First Name");

        Lname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lname.setText("Last Name");

        IDnum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDnum.setText("ID Number");

        Birthdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Birthdate.setText("Birth Date");

        Phonenum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Phonenum.setText("Phone Number");

        Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Email.setText("Email");

        javax.swing.GroupLayout bluebox4Layout = new javax.swing.GroupLayout(bluebox4);
        bluebox4.setLayout(bluebox4Layout);
        bluebox4Layout.setHorizontalGroup(
            bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluebox4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bluebox4Layout.createSequentialGroup()
                        .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fname)
                            .addComponent(Lname)
                            .addComponent(IDnum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Lnamebox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(Fnamebox2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDbox))
                        .addGap(18, 18, 18)
                        .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bluebox4Layout.createSequentialGroup()
                                .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Birthdate)
                                    .addComponent(Phonenum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(birthdatebox)
                                    .addComponent(phonenumbox)))
                            .addGroup(bluebox4Layout.createSequentialGroup()
                                .addComponent(Email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bluebox4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(personalinfo2)
                        .addGap(147, 147, 147))))
        );
        bluebox4Layout.setVerticalGroup(
            bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluebox4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personalinfo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bluebox4Layout.createSequentialGroup()
                        .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fnamebox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDnum)
                            .addComponent(emailbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email)))
                    .addGroup(bluebox4Layout.createSequentialGroup()
                        .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birthdatebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Birthdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bluebox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonenumbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Phonenum))
                        .addGap(46, 46, 46)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(bluebox4);
        bluebox4.setBounds(10, 150, 470, 180);

        bluebox5.setBackground(new java.awt.Color(0, 204, 204));
        bluebox5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Cardinfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cardinfo.setText("Card Information");

        cardnumbox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cardnumbox.setText("XXXX XXXX XXXX XXXX");
        cardnumbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardnumboxActionPerformed(evt);
            }
        });

        expdatebox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        expdatebox.setText("XX / XXXX");
        expdatebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expdateboxActionPerformed(evt);
            }
        });

        cvvbox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cvvbox.setText("XXX");
        cvvbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvboxActionPerformed(evt);
            }
        });

        zipcodebox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        zipcodebox.setText("XXXXX");
        zipcodebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeboxActionPerformed(evt);
            }
        });

        billingaddbox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        billingaddbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingaddboxActionPerformed(evt);
            }
        });

        cardnum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cardnum.setText("Card Number");

        expdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        expdate.setText("Expiration Date");

        cvv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cvv.setText("CVV code");

        zipcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zipcode.setText("Zip Code");

        billingadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        billingadd.setText("Billing Address");

        javax.swing.GroupLayout bluebox5Layout = new javax.swing.GroupLayout(bluebox5);
        bluebox5.setLayout(bluebox5Layout);
        bluebox5Layout.setHorizontalGroup(
            bluebox5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluebox5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bluebox5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bluebox5Layout.createSequentialGroup()
                        .addGroup(bluebox5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cardnum)
                            .addComponent(expdate))
                        .addGap(18, 18, 18)
                        .addGroup(bluebox5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cardnumbox)
                            .addComponent(expdatebox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bluebox5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bluebox5Layout.createSequentialGroup()
                                .addComponent(zipcode)
                                .addGap(18, 18, 18)
                                .addComponent(zipcodebox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bluebox5Layout.createSequentialGroup()
                                .addComponent(cvv)
                                .addGap(18, 18, 18)
                                .addComponent(cvvbox))))
                    .addGroup(bluebox5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(billingadd)
                        .addGap(18, 18, 18)
                        .addComponent(billingaddbox, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bluebox5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cardinfo)
                .addGap(164, 164, 164))
        );
        bluebox5Layout.setVerticalGroup(
            bluebox5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluebox5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Cardinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bluebox5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardnumbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardnum)
                    .addComponent(zipcodebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bluebox5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expdatebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expdate)
                    .addComponent(cvvbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bluebox5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billingaddbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billingadd))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(bluebox5);
        bluebox5.setBounds(10, 370, 470, 200);

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(190, 620, 120, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/background photo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Fnamebox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fnamebox2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Fnamebox2ActionPerformed

    private void LnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_LnameboxActionPerformed

    private void IDboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_IDboxActionPerformed

    private void birthdateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdateboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_birthdateboxActionPerformed

    private void phonenumboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_phonenumboxActionPerformed

    private void emailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_emailboxActionPerformed

    private void cardnumboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardnumboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cardnumboxActionPerformed

    private void expdateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expdateboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_expdateboxActionPerformed

    private void cvvboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cvvboxActionPerformed

    private void zipcodeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_zipcodeboxActionPerformed

    private void billingaddboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingaddboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_billingaddboxActionPerformed

    static String modifyFile(String oldString, String newString) {
        
        
        File database = new File("Database.txt");

        String oldContent = "";

        BufferedReader reader = null;

        FileWriter writer = null;

        try {
            reader = new BufferedReader(new FileReader(database));

            //Reading all the lines of input text file into oldContent
            String line = reader.readLine();

            while (line != null) {
                oldContent = oldContent + line + System.lineSeparator();

                line = reader.readLine();
            }

            //Replacing oldString with newString in the oldContent
            String newContent = oldContent.replaceAll(oldString, newString);

            //Rewriting the input text file with newContent
            writer = new FileWriter(database);

            writer.write(newContent);

            reader.close();
            writer.close();
            
        } catch (IOException e) {
        }

        return "";
                    
    }


    //save edit button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //new Homepage().setVisible(true);
        
        try {

            PrintWriter fileWriter = new PrintWriter(new FileWriter(database, true));

            BufferedWriter bw = new BufferedWriter(fileWriter);
            BufferedReader br = new BufferedReader(new FileReader(database));

            Scanner sc2 = new Scanner(database);

            //String enterusername = usernamebox.getText();
            //char[] enterpassword = passwordbox.getPassword();
            String name = "First Name:";
            String last = "Last Name:";
            String id = "ID:";
            String bd = "Birth Date:";
            String pn = "Phone Number:";
            String email = "Email:";

            String cn = "Card Number:";
            String cvv = "cvv:";
            String exp = "Exp. Date:";
            String zip = "Zip Code:";
            String ba = "Billing Address:";

            boolean found = false; // added this variable

            while (sc2.hasNextLine()) {

                String input = sc2.nextLine();

                if (input.equals(name)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    modifyFile(sc2.nextLine(), profileedit.Fnamebox2.getText());
                    
                }
                
                if (input.equals(last)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    //Profilepage.Lnamebox.setText(sc2.next());
                    modifyFile(sc2.nextLine(), profileedit.Lnamebox.getText());
                }

                if (input.equals(id)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    //Profilepage.IDbox.setText(sc2.nextLine());
                    modifyFile(sc2.nextLine(), profileedit.IDbox.getText());
                }

                if (input.equals(bd)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    //Profilepage.birthdatebox.setText(sc2.nextLine());
                    modifyFile(sc2.nextLine(), profileedit.birthdatebox.getText());
                }

                if (input.equals(pn)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    //Profilepage.phonenumbox.setText(sc2.nextLine());
                    modifyFile(sc2.nextLine(), profileedit.phonenumbox.getText());
                }

                if (input.equals(email)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    //Profilepage.emailbox.setText(sc2.nextLine());
                    modifyFile(sc2.nextLine(), profileedit.emailbox.getText());
                }

                if (input.equals(cn)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    //Profilepage.cardnumbox.setText(sc2.nextLine());
                    modifyFile(sc2.nextLine(), profileedit.cardnumbox.getText());
                }

                if (input.equals(cvv)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    //Profilepage.cvvbox.setText(sc2.nextLine());
                    modifyFile(sc2.nextLine(), profileedit.cvvbox.getText());

                }

                if (input.equals(exp)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    //Profilepage.expdatebox.setText(sc2.nextLine());
                    modifyFile(sc2.nextLine(), profileedit.expdatebox.getText());
                }

                if (input.equals(zip)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    //Profilepage.zipcodebox.setText(sc2.nextLine());
                    modifyFile(sc2.nextLine(), profileedit.zipcodebox.getText());
                }

                if (input.equals(ba)) {
                    found = true;
                    //System.out.println(sc2.nextLine());
                    //Profilepage.billingaddbox.setText(sc2.nextLine());
                    modifyFile(sc2.nextLine(), profileedit.billingaddbox.getText());
                }

            }

            if (!found) { // added the contents of the previously existing else statement here, outside the while
                JOptionPane.showMessageDialog(null,
                        "Database is empty.",
                        "Error Message",
                        JOptionPane.ERROR_MESSAGE);

            }
            
            
            JOptionPane.showMessageDialog(null, "Changes have been saved");
            
            bw.close();
            
            new Homepage().setVisible(true);
        this.dispose();
            
        } catch (IOException ex) {
            Logger.getLogger(LogInpage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profileedit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profileedit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profileedit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profileedit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profileedit().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Birthdate;
    private javax.swing.JLabel Cardinfo;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fname;
    public static javax.swing.JTextField Fnamebox2;
    public static javax.swing.JTextField IDbox;
    private javax.swing.JLabel IDnum;
    private javax.swing.JLabel Lname;
    public static javax.swing.JTextField Lnamebox;
    private javax.swing.JLabel Phonenum;
    private javax.swing.JLabel billingadd;
    public static javax.swing.JTextField billingaddbox;
    public static javax.swing.JTextField birthdatebox;
    private javax.swing.JPanel bluebox4;
    private javax.swing.JPanel bluebox5;
    private javax.swing.JLabel cardnum;
    public static javax.swing.JTextField cardnumbox;
    private javax.swing.JLabel cvv;
    public static javax.swing.JTextField cvvbox;
    public static javax.swing.JTextField emailbox;
    private javax.swing.JLabel expdate;
    public static javax.swing.JTextField expdatebox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel personalinfo2;
    public static javax.swing.JTextField phonenumbox;
    private javax.swing.JLabel zipcode;
    public static javax.swing.JTextField zipcodebox;
    // End of variables declaration//GEN-END:variables
}
