package iac.app;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static iac.app.ReserveDoctor_BOOKING.RB;

/**
 *
 * @author Jana Omar Baqays 1805288
 */
public class ReserveDoctor_CONFIRM extends javax.swing.JFrame {

    /**
     * created a new form ReserveDoctor_CONFIRM.
     */
    public static ReserveDoctor_CONFIRM RC = new ReserveDoctor_CONFIRM();

    /**
     * Creates new form ReserveDoctor_CONFIRM.
     */
    public ReserveDoctor_CONFIRM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOGO = new javax.swing.JLabel();
        AppointmentChoosenConfirm = new javax.swing.JLabel();
        AppointmentChoosenConfirm_dr = new javax.swing.JLabel();
        AppointmentChoosenConfirm_time = new javax.swing.JLabel();
        AppointmentChoosenConfirm_day = new javax.swing.JLabel();
        AppointmentChoosenConfirm_date = new javax.swing.JLabel();
        Cancel_Button = new javax.swing.JButton();
        Confirm_Button = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/doctor-pet.png"))); // NOI18N
        LOGO.setText("Reserve Doctor");
        getContentPane().add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 260, 100));

        AppointmentChoosenConfirm.setBackground(new java.awt.Color(255, 255, 255));
        AppointmentChoosenConfirm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AppointmentChoosenConfirm.setForeground(new java.awt.Color(102, 102, 102));
        AppointmentChoosenConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AppointmentChoosenConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 250, 40));

        AppointmentChoosenConfirm_dr.setBackground(new java.awt.Color(255, 255, 255));
        AppointmentChoosenConfirm_dr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AppointmentChoosenConfirm_dr.setForeground(new java.awt.Color(102, 102, 102));
        AppointmentChoosenConfirm_dr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AppointmentChoosenConfirm_dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 250, 40));

        AppointmentChoosenConfirm_time.setBackground(new java.awt.Color(255, 255, 255));
        AppointmentChoosenConfirm_time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AppointmentChoosenConfirm_time.setForeground(new java.awt.Color(102, 102, 102));
        AppointmentChoosenConfirm_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AppointmentChoosenConfirm_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 250, 40));

        AppointmentChoosenConfirm_day.setBackground(new java.awt.Color(255, 255, 255));
        AppointmentChoosenConfirm_day.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AppointmentChoosenConfirm_day.setForeground(new java.awt.Color(102, 102, 102));
        AppointmentChoosenConfirm_day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AppointmentChoosenConfirm_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 250, 40));

        AppointmentChoosenConfirm_date.setBackground(new java.awt.Color(255, 255, 255));
        AppointmentChoosenConfirm_date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AppointmentChoosenConfirm_date.setForeground(new java.awt.Color(102, 102, 102));
        AppointmentChoosenConfirm_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AppointmentChoosenConfirm_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 250, 40));

        Cancel_Button.setBackground(new java.awt.Color(255, 153, 0));
        Cancel_Button.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Cancel_Button.setForeground(new java.awt.Color(255, 255, 255));
        Cancel_Button.setText("Cancel");
        Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, -1, -1));

        Confirm_Button.setBackground(new java.awt.Color(255, 153, 0));
        Confirm_Button.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Confirm_Button.setForeground(new java.awt.Color(255, 255, 255));
        Confirm_Button.setText("Confirm");
        Confirm_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/background photo.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 715));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * This method is called Cancel_ButtonActionPerformed that cancel the
     * Reservation and go to the Previous form.
     *
     * @param ActionEvent the action of button will run the code inside the
     * method and display the form we want it.
     */
    private void Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_ButtonActionPerformed
        RC.setVisible(false);
        ReserveDoctor_BOOKING RB = new ReserveDoctor_BOOKING();
        RB.setVisible(true);
    }//GEN-LAST:event_Cancel_ButtonActionPerformed
    /**
     * This method is called Confirm_ButtonActionPerformed that cancel the
     * Reservation and go to the confirmed massege form and call the method thet
     * will delete the Reservation appointment from list and JComboBox and file.
     *
     * @param ActionEvent the action of button will run the code inside the
     * method and display the form we want it.
     */
    private void Confirm_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_ButtonActionPerformed
        RC.setVisible(false);
        try {
            RB.DeleteAnAppointment();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ReserveDoctor_CONFIRM.class.getName()).log(Level.SEVERE, null, ex);
        }
        ReserveDoctor_CONFIRMED RCD = new ReserveDoctor_CONFIRMED();
        RCD.setVisible(true);
    }//GEN-LAST:event_Confirm_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReserveDoctor_CONFIRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReserveDoctor_CONFIRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReserveDoctor_CONFIRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReserveDoctor_CONFIRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RC.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel AppointmentChoosenConfirm;
    public static javax.swing.JLabel AppointmentChoosenConfirm_date;
    public static javax.swing.JLabel AppointmentChoosenConfirm_day;
    public static javax.swing.JLabel AppointmentChoosenConfirm_dr;
    public static javax.swing.JLabel AppointmentChoosenConfirm_time;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Cancel_Button;
    private javax.swing.JButton Confirm_Button;
    private javax.swing.JLabel LOGO;
    // End of variables declaration//GEN-END:variables

    /**
     * this method will print all informtion of the Appointment user Choosen in
     * labels.
     *
     * @param AppointmentChoosen is the value that in it the information of
     * appointment.
     */
    public void setAppointmentChoosenConfirm(String AppointmentChoosen) {
        String[] str = AppointmentChoosen.split(",");
        this.AppointmentChoosenConfirm.setText(str[0]);
        this.AppointmentChoosenConfirm_dr.setText(str[1]);
        this.AppointmentChoosenConfirm_time.setText(str[2]);
        this.AppointmentChoosenConfirm_day.setText(str[3]);
        this.AppointmentChoosenConfirm_date.setText(str[4]);
    }

}
