/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iac.app;

import java.io.*;
import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nooralsharif
 */
public class SignupPT2 extends java.awt.Frame {

    
    public File database = new File("Database.txt");
    
    
    /**
     * Creates new form SignupPT2
     */
    public SignupPT2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tealbox = new javax.swing.JPanel();
        boxlogo = new javax.swing.JLabel();
        newmember = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();
        bluebox2 = new javax.swing.JPanel();
        Cardinfo = new javax.swing.JLabel();
        cardnumbox = new javax.swing.JTextField();
        expdatebox = new javax.swing.JTextField();
        cvvbox = new javax.swing.JTextField();
        zipcodebox = new javax.swing.JTextField();
        billingaddbox = new javax.swing.JTextField();
        cardnum = new javax.swing.JLabel();
        expdate = new javax.swing.JLabel();
        cvv = new javax.swing.JLabel();
        zipcode = new javax.swing.JLabel();
        billingadd = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        signupnext = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 715));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        tealbox.setBackground(new java.awt.Color(0, 153, 153));
        tealbox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tealbox.setPreferredSize(new java.awt.Dimension(341, 128));

        boxlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/square logo.png"))); // NOI18N
        boxlogo.setText("jLabel1");

        newmember.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newmember.setText("New Member");

        signup.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        signup.setText("Signup");

        javax.swing.GroupLayout tealboxLayout = new javax.swing.GroupLayout(tealbox);
        tealbox.setLayout(tealboxLayout);
        tealboxLayout.setHorizontalGroup(
            tealboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tealboxLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(boxlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(tealboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newmember)
                    .addComponent(signup))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        tealboxLayout.setVerticalGroup(
            tealboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tealboxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tealboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tealboxLayout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(newmember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(boxlogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bluebox2.setBackground(new java.awt.Color(0, 204, 204));
        bluebox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Cardinfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cardinfo.setText("Card Information");

        cardnumbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cardnumbox.setText("XXXX XXXX XXXX XXXX");
        cardnumbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardnumboxActionPerformed(evt);
            }
        });

        expdatebox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        expdatebox.setText("XX / XXXX");
        expdatebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expdateboxActionPerformed(evt);
            }
        });

        cvvbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cvvbox.setText("XXX");
        cvvbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvboxActionPerformed(evt);
            }
        });

        zipcodebox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zipcodebox.setText("XXXXX");
        zipcodebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeboxActionPerformed(evt);
            }
        });

        billingaddbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        billingaddbox.setText("neigborhood");
        billingaddbox.setToolTipText("");
        billingaddbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingaddboxActionPerformed(evt);
            }
        });

        cardnum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cardnum.setText("Card Number");

        expdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        expdate.setText("Expiration Date");

        cvv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cvv.setText("CVV code");

        zipcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zipcode.setText("Zip Code");

        billingadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billingadd.setText("Billing Address");

        javax.swing.GroupLayout bluebox2Layout = new javax.swing.GroupLayout(bluebox2);
        bluebox2.setLayout(bluebox2Layout);
        bluebox2Layout.setHorizontalGroup(
            bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluebox2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bluebox2Layout.createSequentialGroup()
                        .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cardnum)
                            .addComponent(expdate)
                            .addComponent(cvv)
                            .addComponent(zipcode)
                            .addComponent(billingadd))
                        .addGap(18, 18, 18)
                        .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billingaddbox, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(zipcodebox, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cvvbox, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(expdatebox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                            .addComponent(cardnumbox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bluebox2Layout.createSequentialGroup()
                        .addComponent(Cardinfo)
                        .addGap(114, 114, 114))))
        );
        bluebox2Layout.setVerticalGroup(
            bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluebox2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Cardinfo)
                .addGap(18, 18, 18)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardnumbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardnum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expdatebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expdate))
                .addGap(18, 18, 18)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvvbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvv))
                .addGap(22, 22, 22)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcodebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcode))
                .addGap(18, 18, 18)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billingaddbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billingadd))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        back.setBackground(new java.awt.Color(255, 153, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        signupnext.setBackground(new java.awt.Color(255, 153, 0));
        signupnext.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        signupnext.setForeground(new java.awt.Color(255, 255, 255));
        signupnext.setText("Signup");
        signupnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupnextActionPerformed(evt);
            }
        });

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/background photo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tealbox, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(signupnext, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(bluebox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(BackgroundImage)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tealbox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(430, 430, 430)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupnext, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(bluebox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(BackgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void cardnumboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardnumboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardnumboxActionPerformed

    private void expdateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expdateboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expdateboxActionPerformed

    private void cvvboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvboxActionPerformed

    private void zipcodeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeboxActionPerformed

    private void billingaddboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingaddboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billingaddboxActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new SignupPT1().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_backActionPerformed

    private void signupnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupnextActionPerformed
        // TODO add your handling code here:
        try {
            
            PrintWriter fileWriter = new PrintWriter(new FileWriter(database, true));
    
            BufferedWriter br = new BufferedWriter(fileWriter);
            
            br.append("\n\n---------------CARD INFO-----------------");
            
            br.append("\n"+"Card Number:");
            String card = cardnumbox.getText();
            br.append("\n"+card);
        
            br.append("\n"+"cvv:");
            String cvv = cvvbox.getText();
            br.append("\n"+cvv);
            
            br.append("\n"+"Exp. Data:");
            String exp = expdatebox.getText();
            br.append("\n"+exp);
            
            br.append("\n"+"Zip Code:");
            String zip = zipcodebox.getText();
            br.append("\n"+zip);
            
            br.append("\n"+"Billing Address:");
            String addr = billingaddbox.getText();
            br.append("\n"+addr);
           
            //////SAVE ADDRESS IN NEW FILE:
            File user_neiborhood = new File("user_neighborhood.txt");
            
            PrintWriter fW = new PrintWriter(new FileWriter(user_neiborhood, true));
    
            BufferedWriter bwrite = new BufferedWriter(fW);
            
            BufferedReader bread = new BufferedReader(new FileReader(database));
            
            Scanner scan = new Scanner(database);
            
            String fname = "First Name:";
            String ba = "Billing Address:";
            
            boolean found = false; // added this variable

            while (scan.hasNextLine()) {
                
                String input = scan.nextLine();

                if (input.equals(fname)) {
                    found = true;
                    bwrite.append(scan.nextLine());
                    bwrite.append(",,");
                }
              
                if (input.equals(ba)) {
                    found = true;
                    bwrite.append(scan.nextLine());
                    
                    /*
                    String add = "";
                    
                    String[] address = add.split(", ");
                    
                    
                    for(int i = 0 ; i<address.length ; i++){
                        
                        add = scan.nextLine();
                        
                        System.out.println(Arrays.toString(address).replace("[", "").replace("]", ""));
                    }
                    
                    //System.out.println(Arrays.toString(address).replace("[", "").replace("]", ""));
                    */
                }
                
                
                
            }
            
            bwrite.close();
            bread.close();
            
            ////////////////////////////////////////////////////////////////////////////////////////
            
            br.append("\n\n----------------LOGIN INFO-----------------");
            br.append("\nUsername\n");
            
            BufferedReader read = new BufferedReader(new FileReader(database));
            String text = read.readLine(); 
            String text2 = read.readLine();
            String userFname = read.readLine();
            // Stop. text is the first line.
            
            //System.out.println(userFname);
            
            String[] strArray = text.split(",");
            
            //System.out.println(Arrays.toString(strArray).replace("[", "").replace("]", ""));
            
            //System.out.println(userFname);
            br.append(userFname);
            
            
            ////////////////////////////////////////////////////////////////////////////////////////
            
            int leftLimit = 48; // numeral '0'
            int rightLimit = 122; // letter 'z'
            int targetStringLength = 6;
            Random random = new Random();

            String password = random.ints(leftLimit, rightLimit + 1)
                    .filter(i -> (i <= 57 || i >= 65) && (i <= 90 || i >= 97))
                    .limit(targetStringLength)
                    .collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append)
                    .toString();

            //System.out.println(password);
            
            br.append("\nPassword\n");
            
            
            ////////////////////////////////////////////////////////////////////////////////////////
            
            
            JOptionPane.showMessageDialog(null, "Your Username is:\n"+ userFname +"\nYour Password is:\n"+ password);
            
            
            br.append(password);
            
            br.close();
            
            
            
            
            
        } catch (IOException ex) {
            Logger.getLogger(SignupPT2.class.getName()).log(Level.SEVERE, null, ex);
        
        }    
        
        
        new Homepage().setVisible(true);
        //this.dispose();
        
    }//GEN-LAST:event_signupnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPT2().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel Cardinfo;
    private javax.swing.JButton back;
    private javax.swing.JLabel billingadd;
    public static javax.swing.JTextField billingaddbox;
    private javax.swing.JPanel bluebox2;
    private javax.swing.JLabel boxlogo;
    private javax.swing.JLabel cardnum;
    public static javax.swing.JTextField cardnumbox;
    private javax.swing.JLabel cvv;
    public static javax.swing.JTextField cvvbox;
    private javax.swing.JLabel expdate;
    public static javax.swing.JTextField expdatebox;
    private javax.swing.JLabel newmember;
    private javax.swing.JLabel signup;
    private javax.swing.JButton signupnext;
    private javax.swing.JPanel tealbox;
    private javax.swing.JLabel zipcode;
    public static javax.swing.JTextField zipcodebox;
    // End of variables declaration//GEN-END:variables
}
