/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iac.app;

/**
 *
 * @author nooralsharif
 */

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class SignupPT1 extends javax.swing.JFrame {

    /**
     * Creates new form SignupPT1
     */
    
    //public BufferedWriter add2Data;
    
    public File database = new File("Database.txt");
    
    
    public SignupPT1() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tealbox = new javax.swing.JPanel();
        boxlogo = new javax.swing.JLabel();
        newmember = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        next = new javax.swing.JButton();
        bluebox2 = new javax.swing.JPanel();
        personalinfo = new javax.swing.JLabel();
        Fnamebox = new javax.swing.JTextField();
        Lnamebox = new javax.swing.JTextField();
        IDbox = new javax.swing.JTextField();
        birthdatebox = new javax.swing.JTextField();
        phonenumbox = new javax.swing.JTextField();
        emailbox = new javax.swing.JTextField();
        Fname = new javax.swing.JLabel();
        Lname = new javax.swing.JLabel();
        IDnum = new javax.swing.JLabel();
        Birthdate = new javax.swing.JLabel();
        Phonenum = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 715));
        setMinimumSize(new java.awt.Dimension(500, 715));
        setPreferredSize(new java.awt.Dimension(500, 715));

        tealbox.setBackground(new java.awt.Color(0, 153, 153));
        tealbox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        boxlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/square logo.png"))); // NOI18N
        boxlogo.setText("jLabel1");

        newmember.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newmember.setText("New Member");

        signup.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        signup.setText("Signup");

        javax.swing.GroupLayout tealboxLayout = new javax.swing.GroupLayout(tealbox);
        tealbox.setLayout(tealboxLayout);
        tealboxLayout.setHorizontalGroup(
            tealboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tealboxLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(boxlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(tealboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newmember)
                    .addComponent(signup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tealboxLayout.setVerticalGroup(
            tealboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tealboxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tealboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tealboxLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(newmember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(boxlogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        cancel.setBackground(new java.awt.Color(255, 153, 0));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        next.setBackground(new java.awt.Color(255, 153, 0));
        next.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        bluebox2.setBackground(new java.awt.Color(0, 204, 204));
        bluebox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        personalinfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        personalinfo.setText("Personal Information");

        Fnamebox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameboxActionPerformed(evt);
            }
        });

        Lnamebox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameboxActionPerformed(evt);
            }
        });

        IDbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDboxActionPerformed(evt);
            }
        });

        birthdatebox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        birthdatebox.setText("XX / XX / XXXX");
        birthdatebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateboxActionPerformed(evt);
            }
        });

        phonenumbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phonenumbox.setText("5XXXXXXXX");
        phonenumbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumboxActionPerformed(evt);
            }
        });

        emailbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailbox.setText("EXAMPLE @ EXAMPLE.COM");
        emailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailboxActionPerformed(evt);
            }
        });

        Fname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Fname.setText("First Name");

        Lname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lname.setText("Last Name");

        IDnum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IDnum.setText("ID Number");

        Birthdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Birthdate.setText("Birth Date");

        Phonenum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Phonenum.setText("Phone Number");

        Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email.setText("Email");

        javax.swing.GroupLayout bluebox2Layout = new javax.swing.GroupLayout(bluebox2);
        bluebox2.setLayout(bluebox2Layout);
        bluebox2Layout.setHorizontalGroup(
            bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluebox2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bluebox2Layout.createSequentialGroup()
                        .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fname)
                            .addComponent(Lname)
                            .addComponent(IDnum)
                            .addComponent(Birthdate)
                            .addComponent(Phonenum)
                            .addComponent(Email))
                        .addGap(18, 18, 18)
                        .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailbox, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(IDbox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lnamebox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fnamebox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(birthdatebox)
                            .addComponent(phonenumbox))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bluebox2Layout.createSequentialGroup()
                        .addComponent(personalinfo)
                        .addGap(114, 114, 114))))
        );
        bluebox2Layout.setVerticalGroup(
            bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluebox2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(personalinfo)
                .addGap(18, 18, 18)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lname))
                .addGap(18, 18, 18)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDnum))
                .addGap(22, 22, 22)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdatebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Birthdate))
                .addGap(18, 18, 18)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonenumbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phonenum))
                .addGap(18, 18, 18)
                .addGroup(bluebox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/background photo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tealbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bluebox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tealbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bluebox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameboxActionPerformed

    private void IDboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDboxActionPerformed

    private void birthdateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdateboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdateboxActionPerformed

    private void phonenumboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumboxActionPerformed

    private void emailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailboxActionPerformed

    private void FnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameboxActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_FnameboxActionPerformed

    
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        
        try {
            
            PrintWriter fileWriter = new PrintWriter(new FileWriter(database, true));
    
            BufferedWriter br = new BufferedWriter(fileWriter);
            
            br.append("-----------------USER INFO-----------------");
            
            br.append("\n"+"First Name:");
            String fname = Fnamebox.getText();
            br.append("\n"+fname);
            
            br.append("\n"+"Last Name:");
            String Lname = Lnamebox.getText();
            br.append("\n"+Lname);
            
            br.append("\n"+"ID:");
            String ID = IDbox.getText();
            br.append("\n"+ID);
            
            br.append("\n"+"Birth Date:");
            String Bdate = birthdatebox.getText();
            br.append("\n"+Bdate);
            
            br.append("\n"+"Phone Number:");
            String phonenum = phonenumbox.getText();
            br.append("\n"+phonenum);
            
            br.append("\n"+"Email:");
            String email = emailbox.getText();
            br.append("\n"+email);
            
            
            br.close();
            
        } catch (IOException ex) {
            Logger.getLogger(SignupPT1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        new SignupPT2().setVisible(true);
        //this.dispose();
        
        
    }//GEN-LAST:event_nextActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        new Startpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPT1().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel Birthdate;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fname;
    public static javax.swing.JTextField Fnamebox;
    public static javax.swing.JTextField IDbox;
    private javax.swing.JLabel IDnum;
    private javax.swing.JLabel Lname;
    public static javax.swing.JTextField Lnamebox;
    private javax.swing.JLabel Phonenum;
    public static javax.swing.JTextField birthdatebox;
    private javax.swing.JPanel bluebox2;
    private javax.swing.JLabel boxlogo;
    private javax.swing.JButton cancel;
    public static javax.swing.JTextField emailbox;
    private javax.swing.JLabel newmember;
    private javax.swing.JButton next;
    private javax.swing.JLabel personalinfo;
    public static javax.swing.JTextField phonenumbox;
    private javax.swing.JLabel signup;
    private javax.swing.JPanel tealbox;
    // End of variables declaration//GEN-END:variables
}
