/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iac.app;

/**
 *
 * @author nooralsharif
 */
public class Startpage extends javax.swing.JFrame {

    /**
     * Creates new form Startpage
     */
    public Startpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        AppLogoWIGHTbackground = new javax.swing.JPanel();
        AppLogo = new javax.swing.JLabel();
        ButtonsTEALBackground = new javax.swing.JPanel();
        Login = new javax.swing.JButton();
        Signup = new javax.swing.JButton();
        copyright = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 715));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 715));

        background.setLayout(null);

        AppLogoWIGHTbackground.setBackground(new java.awt.Color(255, 255, 255));

        AppLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/logo2.png"))); // NOI18N

        javax.swing.GroupLayout AppLogoWIGHTbackgroundLayout = new javax.swing.GroupLayout(AppLogoWIGHTbackground);
        AppLogoWIGHTbackground.setLayout(AppLogoWIGHTbackgroundLayout);
        AppLogoWIGHTbackgroundLayout.setHorizontalGroup(
            AppLogoWIGHTbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppLogoWIGHTbackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(AppLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        AppLogoWIGHTbackgroundLayout.setVerticalGroup(
            AppLogoWIGHTbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppLogoWIGHTbackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AppLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(AppLogoWIGHTbackground);
        AppLogoWIGHTbackground.setBounds(100, 120, 300, 130);

        ButtonsTEALBackground.setBackground(new java.awt.Color(0, 153, 153));
        ButtonsTEALBackground.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Login.setBackground(new java.awt.Color(255, 153, 0));
        Login.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Signup.setBackground(new java.awt.Color(255, 153, 0));
        Signup.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Signup.setForeground(new java.awt.Color(255, 255, 255));
        Signup.setText("Signup");
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsTEALBackgroundLayout = new javax.swing.GroupLayout(ButtonsTEALBackground);
        ButtonsTEALBackground.setLayout(ButtonsTEALBackgroundLayout);
        ButtonsTEALBackgroundLayout.setHorizontalGroup(
            ButtonsTEALBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsTEALBackgroundLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ButtonsTEALBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        ButtonsTEALBackgroundLayout.setVerticalGroup(
            ButtonsTEALBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsTEALBackgroundLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        background.add(ButtonsTEALBackground);
        ButtonsTEALBackground.setBounds(90, 290, 310, 250);

        copyright.setText("Copyright © 2020 IAC all rights reserved");
        background.add(copyright);
        copyright.setBounds(130, 600, 240, 50);

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iac/app/background photo.jpg"))); // NOI18N
        background.add(BackgroundImage);
        BackgroundImage.setBounds(0, 0, 500, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        new LogInpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginActionPerformed

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
        // TODO add your handling code here:
        new SignupPT1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppLogo;
    private javax.swing.JPanel AppLogoWIGHTbackground;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel ButtonsTEALBackground;
    private javax.swing.JButton Login;
    private javax.swing.JButton Signup;
    private javax.swing.JPanel background;
    private javax.swing.JLabel copyright;
    // End of variables declaration//GEN-END:variables
}
